sonar.organization=escthedeadline
sonar.projectKey=escthedeadline_uday-devopsec-frontend
sonar.projectName=OPM Frontend App
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.jsx,**/*.test.js,**/nginx.conf
sonar.sourceEncoding=UTF-8
sonar.language=js
